<?php

namespace Tests\Feature\Services\Client;

use App\Data\Models\Client;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\Response;
use Tests\TestCase;

class DeleteClientFeatureTest extends TestCase
{
    use RefreshDatabase;

    protected Client $client;

    /**
     * @test
     */
    public function feature_should_pass_when_client_found()
    {
        $res = $this->getJson(route('clients.destroy', ['client' => $this->client->getId()]));
        $this->assertEquals(true, $this->client->delete());
        $this->assertEquals(Response::HTTP_OK, $res->status());
    }

    /**
     * @test
     */
    public function feature_should_failed_when_client_not_found()
    {
        $res = $this->getJson(route('clients.destroy', ['client' => 2]));
        $this->assertEquals(Response::HTTP_NOT_FOUND, $res->status());
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = Client::factory()->create()->first();
    }
}
