<?php

namespace Tests\Feature\Services\Client;

use App\Data\Models\Client;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Http\Response;
use Tests\TestCase;

class UpdateClientFeatureTest extends TestCase
{
    use RefreshDatabase, WithFaker;


    /**
     * @var Client
     */
    private Client $client;

    /**
     * @var string
     */
    private string $name;

    /**
     * @var string
     */
    private string $email;

    /**
     * @test
     */
    public function feature_should_pass_when_client_exists()
    {
        $this->assertNotEmpty($this->client);
    }

    /**
     * @test
     */
    public function feature_should_pass_when_client_updated()
    {
        $firstName = $this->client->getFirstName();
        $res = $this->putJson(route('clients.update', ['client' => $this->client->getId()]), [
            'firstName' => $this->name,
            'lastName' => $this->name,
            'email' => $this->email,
            'phoneNumber' => $this->phone,
        ]);
        $this->assertEquals(Response::HTTP_ACCEPTED, $res->getStatusCode());
        $this->assertNotEquals($firstName, $res->json('data')['client']['firstName']);
    }

    /**
     * @test
     */
    public function feature_should_failed_when_client_not_found()
    {
        $res = $this->putJson(route('clients.update', ['client' => 2]), [
            'firstName' => $this->name,
            'lastName' => $this->name,
            'email' => $this->email,
            'phoneNumber' => $this->phone,
        ]);
        $this->assertEquals(Response::HTTP_NOT_FOUND, $res->getStatusCode());
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = Client::factory()->create()->first();
        $this->name = $this->faker->regexify('[A-Za-z]{2,32}');
        $this->email = $this->faker->email;
        $this->phone = $this->faker->e164PhoneNumber;
    }


}
